
import Criação_Planilha
import matplotlib.pyplot as plt
import numpy as np
from numba import njit

def Plotar_Potencia():  
    P_VA_A=Criação_Planilha.Retornar_excel('Dados_Analisador.xlsx','Potencia','A')
    P_VA_B=Criação_Planilha.Retornar_excel('Dados_Analisador.xlsx','Potencia','B')
    P_VA_C=Criação_Planilha.Retornar_excel('Dados_Analisador.xlsx','Potencia','C')   
    P_W_A=Criação_Planilha.Retornar_excel('Dados_Analisador.xlsx','Potencia','D')
    P_W_B=Criação_Planilha.Retornar_excel('Dados_Analisador.xlsx','Potencia','E')
    P_W_C=Criação_Planilha.Retornar_excel('Dados_Analisador.xlsx','Potencia','F')  
    P_VAR_A=Criação_Planilha.Retornar_excel('Dados_Analisador.xlsx','Potencia','G')
    P_VAR_B=Criação_Planilha.Retornar_excel('Dados_Analisador.xlsx','Potencia','H')
    P_VAR_C=Criação_Planilha.Retornar_excel('Dados_Analisador.xlsx','Potencia','I') 
    P_FP_A=Criação_Planilha.Retornar_excel('Dados_Analisador.xlsx','Grandezas','G')
    P_FP_B=Criação_Planilha.Retornar_excel('Dados_Analisador.xlsx','Grandezas','H')
    P_FP_C=Criação_Planilha.Retornar_excel('Dados_Analisador.xlsx','Grandezas','I') 


    plt.style.use('classic')
    plt.subplot(3, 2, 1)
    plt.title('Potencia FASE A')
    plt.ylabel('Potencia')
    plt.xlabel('Tempo (s)')
    plt.plot(P_VA_A, color='m', label='Potencia Aparente')
    plt.plot(P_W_A, color='g', label='Potencia Ativa')
    plt.plot(P_VAR_A, color='r', label='Potencia Reativa')
    plt.legend()
    plt.grid()
    plt.subplot(3, 2, 3)
    plt.title('Potencia FASE B')
    plt.ylabel('Potencia')
    plt.xlabel('Tempo (s)')
    plt.plot(P_VA_B, color='m', label='Potencia Aparente')
    plt.plot(P_W_B, color='g', label='Potencia Ativa')
    plt.plot(P_VAR_B, color='r', label='Potencia Reativa')
    plt.legend()
    plt.grid()
    plt.subplot(3, 2, 5)
    plt.title('Potencia FASE C')
    plt.ylabel('Potencia')
    plt.xlabel('Tempo (s)')
    plt.plot(P_VA_C, color='m', label='Potencia Aparente')
    plt.plot(P_W_C, color='g', label='Potencia Ativa')
    plt.plot(P_VAR_C, color='r', label='Potencia Reativa')
    plt.legend()
    plt.grid()
    plt.subplot(3, 2, 2)
    plt.title('FP FASE A')
    plt.ylim(0,1)
    plt.ylabel('FP')
    plt.xlabel('Tempo (s)')
    plt.plot(P_FP_A, color='y', label='Fp')
    plt.axhline(y=0.92, color='b', label='Fp de Referencia')
    plt.legend()
    plt.grid()
    plt.subplot(3, 2, 4)
    plt.title('FP FASE B')
    plt.ylim(0,1)
    plt.ylabel('FP')
    plt.xlabel('Tempo (s)')
    plt.plot(P_FP_B, color='y', label='Fp')
    plt.axhline(y=0.92, color='b', label='Fp de Referencia')
    plt.legend()
    plt.grid()
    plt.subplot(3, 2, 6)
    plt.title('FP FASE C')
    plt.ylim(0,1)
    plt.ylabel('FP')
    plt.xlabel('Tempo (s)')
    plt.plot(P_FP_C, color='y', label='Fp')
    plt.axhline(y=0.92, color='b', label='Fp de Referencia')
    plt.legend()
    plt.grid()
    plt.tight_layout()
    plt.show()


def Plotar_THD():
    THD_V_A=Criação_Planilha.Retornar_excel('Dados_Analisador.xlsx','THD','A')
    THD_V_B=Criação_Planilha.Retornar_excel('Dados_Analisador.xlsx','THD','B')
    THD_V_C=Criação_Planilha.Retornar_excel('Dados_Analisador.xlsx','THD','C')
    THD_I_A=Criação_Planilha.Retornar_excel('Dados_Analisador.xlsx','THD','D')
    THD_I_B=Criação_Planilha.Retornar_excel('Dados_Analisador.xlsx','THD','E')
    THD_I_C=Criação_Planilha.Retornar_excel('Dados_Analisador.xlsx','THD','F')

    eixo_x_V_A = np.arange(len(THD_V_A))
    eixo_x_V_B = np.arange(len(THD_V_B))
    eixo_x_V_C = np.arange(len(THD_V_C))
    eixo_x_I_A = np.arange(len(THD_I_A))
    eixo_x_I_B = np.arange(len(THD_I_B))
    eixo_x_I_C = np.arange(len(THD_I_C))

    plt.style.use('classic')
    plt.subplot(3,2,1)
    plt.title('THD TENSÃO FASE A')
    plt.xlabel('Tempo(s)')
    plt.ylabel('THD (%)')
    plt.axhline(10,c='r')
    plt.bar(eixo_x_V_A, THD_V_A)
    plt.grid()
    plt.tight_layout()
    plt.subplot(3,2,3)
    plt.title('THD TENSÃO FASE B')
    plt.xlabel('Tempo(s)')
    plt.ylabel('THD (%)')
    plt.axhline(10,c='r')
    plt.bar(eixo_x_V_B, THD_V_B)
    plt.grid()
    plt.tight_layout()
    plt.subplot(3,2,5)
    plt.title('THD TENSÃO FASE C')
    plt.xlabel('Tempo(s)')
    plt.ylabel('THD (%)')
    plt.axhline(10,c='r')
    plt.bar(eixo_x_V_C, THD_V_C)
    plt.grid()
    plt.tight_layout()
    plt.subplot(3,2,2)
    plt.title('THD Corrente FASE A')
    plt.xlabel('Tempo(s)')
    plt.ylabel('THD (%)')
    plt.axhline(10,c='r')
    plt.bar(eixo_x_I_A, THD_I_A)
    plt.grid()
    plt.tight_layout()
    plt.subplot(3,2,4)
    plt.title('THD Corrente FASE B')
    plt.xlabel('Tempo(s)')
    plt.ylabel('THD (%)')
    plt.axhline(10,c='r')
    plt.bar(eixo_x_I_B, THD_I_A)
    plt.grid()
    plt.tight_layout()
    plt.subplot(3,2,6)
    plt.title('THD Corrente FASE C')
    plt.xlabel('Tempo(s)')
    plt.ylabel('THD (%)')
    plt.axhline(10,c='r')
    plt.bar(eixo_x_I_C, THD_I_C)
    plt.grid()
    plt.tight_layout()
    plt.show()


def Plotar_Variação():
    Variação_A=Criação_Planilha.Retornar_excel('Dados_Analisador.xlsx','Variação','A')
    Variação_B=Criação_Planilha.Retornar_excel('Dados_Analisador.xlsx','Variação','B')
    Variação_C=Criação_Planilha.Retornar_excel('Dados_Analisador.xlsx','Variação','C')

    eixo_x_A = np.arange(len(Variação_A))
    eixo_x_B = np.arange(len(Variação_B))
    eixo_x_C = np.arange(len(Variação_C))

    plt.style.use('classic')
    plt.subplot(3, 1, 1)
    plt.title('Variação de Tensão A(%)')
    plt.xlabel('Tempo(s)')
    plt.ylabel('(%)')
    plt.axhline(10,c='r')
    plt.axhline(-10,c='r')
    plt.bar(eixo_x_A, Variação_A)
    plt.grid()
    plt.tight_layout()
    plt.subplot(3, 1, 2)
    plt.title('Variação de Tensão B(%)')
    plt.xlabel('Tempo(s)')
    plt.ylabel('(%)')
    plt.axhline(10,c='r')
    plt.axhline(-10,c='r')
    plt.bar(eixo_x_B, Variação_B)
    plt.grid()
    plt.tight_layout()
    plt.subplot(3, 1, 3)
    plt.title('Variação de Tensão C(%)')
    plt.xlabel('Tempo(s)')
    plt.ylabel('(%)')
    plt.axhline(10,c='r')
    plt.axhline(-10,c='r')
    plt.bar(eixo_x_C, Variação_C)
    plt.grid()
    plt.tight_layout()
    plt.show()



def Plotar_Interrupção():
    Interrupção_A=Criação_Planilha.Retornar_excel('Dados_Analisador.xlsx','Interrupção','A')
    Interrupção_B=Criação_Planilha.Retornar_excel('Dados_Analisador.xlsx','Interrupção','B')
    Interrupção_C=Criação_Planilha.Retornar_excel('Dados_Analisador.xlsx','Interrupção','C')

    eixo_x_A = np.arange(len(Interrupção_A))
    eixo_x_B = np.arange(len(Interrupção_B))
    eixo_x_C = np.arange(len(Interrupção_C))

    plt.style.use('classic')
    plt.subplot(3, 1, 1)
    plt.title('Interrupção na Tensão FASE A')
    plt.ylabel('Tempo de interrupção (s)')
    plt.xlabel('Tempo (s)')
    plt.bar(eixo_x_A, Interrupção_A)
    plt.grid()
    plt.tight_layout()
    plt.subplot(3, 1, 2)
    plt.title('Interrupção na Tensão FASE B')
    plt.ylabel('Tempo de interrupção (s)')
    plt.xlabel('Tempo (s)')
    plt.bar(eixo_x_B, Interrupção_B)
    plt.grid()
    plt.tight_layout()
    plt.subplot(3, 1, 3)
    plt.title('Interrupção na Tensão FASE C')
    plt.ylabel('Tempo de interrupção (s)')
    plt.xlabel('Tempo (s)')
    plt.bar(eixo_x_C, Interrupção_C)
    plt.grid()
    plt.tight_layout()
    plt.show()

def Plotar_Grandezas():
    V_RMS_A=Criação_Planilha.Retornar_excel('Dados_Analisador.xlsx','Grandezas','A')
    V_RMS_B=Criação_Planilha.Retornar_excel('Dados_Analisador.xlsx','Grandezas','B')
    V_RMS_C=Criação_Planilha.Retornar_excel('Dados_Analisador.xlsx','Grandezas','C') 
    I_RMS_A=Criação_Planilha.Retornar_excel('Dados_Analisador.xlsx','Grandezas','D')
    I_RMS_B=Criação_Planilha.Retornar_excel('Dados_Analisador.xlsx','Grandezas','E')
    I_RMS_C=Criação_Planilha.Retornar_excel('Dados_Analisador.xlsx','Grandezas','F') 

    plt.style.use('classic')
    plt.subplot(3, 2, 1)
    plt.title('Tensão FASE A')
    plt.xlabel('Tensão (Vrms)')
    plt.ylabel('Tempo (s)')
    plt.plot(V_RMS_A, color='m')
    plt.grid()
    plt.tight_layout()
    plt.subplot(3, 2, 3)
    plt.title('Tensão FASE B')
    plt.xlabel('Tensão (Vrms)')
    plt.ylabel('Tempo (s)')
    plt.plot(V_RMS_B, color='m')
    plt.grid()
    plt.tight_layout()
    plt.subplot(3, 2, 5)
    plt.title('Tensão FASE C')
    plt.xlabel('Tensão (Vrms)')
    plt.ylabel('Tempo (s)')
    plt.plot(V_RMS_C, color='m')
    plt.grid()
    plt.tight_layout()
    plt.subplot(3, 2, 2)
    plt.title('Corrente FASE A')
    plt.xlabel('Corrente (A)')
    plt.ylabel('Tempo (s)')
    plt.plot(I_RMS_A, color='m')
    plt.grid()
    plt.tight_layout()
    plt.subplot(3, 2, 4)
    plt.title('Corrente FASE B')
    plt.xlabel('Corrente (A)')
    plt.ylabel('Tempo (s)')
    plt.plot(I_RMS_B, color='m')
    plt.grid()
    plt.tight_layout()
    plt.subplot(3, 2, 6)
    plt.title('Corrente FASE C')
    plt.xlabel('Corrente (A)')
    plt.ylabel('Tempo (s)')
    plt.plot(I_RMS_C, color='m')
    plt.grid()
    plt.tight_layout()
    plt.show()


def Plotar_FFT():
    Freq_Tensão_Af=Criação_Planilha.armazenar_excel('Dados_Analisador.xlsx','FFT','A')
    FFT_Tensão_Af= Criação_Planilha.armazenar_excel('Dados_Analisador.xlsx','FFT','B')
    Freq_Tensão_Bf=Criação_Planilha.armazenar_excel('Dados_Analisador.xlsx','FFT','C')
    FFT_Tensão_Bf=Criação_Planilha.armazenar_excel('Dados_Analisador.xlsx','FFT','D')
    Freq_Tensão_Cf=Criação_Planilha.armazenar_excel('Dados_Analisador.xlsx','FFT','E')
    FFT_Tensão_Cf=Criação_Planilha.armazenar_excel('Dados_Analisador.xlsx','FFT','F')
    Freq_Corrente_Af=Criação_Planilha.armazenar_excel('Dados_Analisador.xlsx','FFT','G')
    FFT_Corrente_Af=Criação_Planilha.armazenar_excel('Dados_Analisador.xlsx','FFT','H')
    Freq_Corrente_Bf=Criação_Planilha.armazenar_excel('Dados_Analisador.xlsx','FFT','I')
    FFT_Corrente_Bf=Criação_Planilha.armazenar_excel('Dados_Analisador.xlsx','FFT','J')
    Freq_Corrente_Cf=Criação_Planilha.armazenar_excel('Dados_Analisador.xlsx','FFT','K')
    FFT_Corrente_Cf=Criação_Planilha.armazenar_excel('Dados_Analisador.xlsx','FFT','L')

    plt.style.use('classic')
    plt.subplot(3,2,1)
    plt.title('FFT TENSÃO FASE A')
    plt.xlabel('Frequencia (Hz)')
    plt.ylabel('Energia(V²)')
    plt.xlim(0,3500)
    plt.grid()
    plt.tight_layout()
    plt.plot(Freq_Tensão_Af,FFT_Tensão_Af)
    plt.subplot(3,2,3)
    plt.title('FFT TENSÃO FASE B')
    plt.xlabel('Frequencia (Hz)')
    plt.ylabel('Energia(V²)')
    plt.xlim(0,3500)
    plt.grid()
    plt.tight_layout()
    plt.plot(Freq_Tensão_Bf,FFT_Tensão_Bf)
    plt.subplot(3,2,5)
    plt.title('FFT TENSÃO FASE C')
    plt.xlabel('Frequencia (Hz)')
    plt.ylabel('Energia(V²)')
    plt.xlim(0,3500)
    plt.grid()
    plt.tight_layout()
    plt.plot(Freq_Tensão_Cf,FFT_Tensão_Cf)
    plt.subplot(3,2,2)
    plt.title('FFT Corrente FASE A')
    plt.xlabel('Frequencia (Hz)')
    plt.ylabel('Energia(I²)')
    plt.xlim(0,3500)
    plt.grid()
    plt.tight_layout()
    plt.plot(Freq_Corrente_Af,FFT_Corrente_Af)
    plt.subplot(3,2,4)
    plt.title('FFT Corrente FASE B')
    plt.xlabel('Frequencia (Hz)')
    plt.ylabel('Energia(I²)')
    plt.xlim(0,3500)
    plt.grid()
    plt.tight_layout()
    plt.plot(Freq_Corrente_Bf,FFT_Corrente_Bf)
    plt.subplot(3,2,6)
    plt.title('FFT Corrente FASE C')
    plt.xlabel('Frequencia (Hz)')
    plt.ylabel('Energia(I²)')
    plt.xlim(0,3500)
    plt.grid()
    plt.tight_layout()
    plt.plot(Freq_Corrente_Cf,FFT_Corrente_Cf)
    plt.tight_layout()
    plt.show()

def Plotar_Frequência():
    Freq_A=Criação_Planilha.Retornar_excel('Dados_Analisador.xlsx','Frequência','A')
    Freq_B=Criação_Planilha.Retornar_excel('Dados_Analisador.xlsx','Frequência','B')
    Freq_C=Criação_Planilha.Retornar_excel('Dados_Analisador.xlsx','Frequência','C')

    eixo_x_A = np.arange(len(Freq_A))
    eixo_x_B = np.arange(len(Freq_B))
    eixo_x_C = np.arange(len(Freq_C))
    
    plt.style.use('classic')
    plt.subplot(3, 1, 1)
    plt.title('Frequência de Fase A')
    plt.ylabel('Frequência (Hz)')
    plt.xlabel('Tempo (s)')
    plt.plot(eixo_x_A, Freq_A,c='r')
    plt.grid()
    plt.tight_layout()
    plt.subplot(3, 1, 2)
    plt.title('Frequência de Fase B')
    plt.ylabel('Frequência (Hz)')
    plt.xlabel('Tempo (s)')
    plt.plot(eixo_x_B, Freq_B,c='r')
    plt.grid()
    plt.tight_layout()
    plt.subplot(3, 1, 3)
    plt.title('Frequência de Fase C')
    plt.ylabel('Frequência (Hz)')
    plt.xlabel('Tempo (s)')
    plt.plot(eixo_x_C, Freq_C,c='r')
    plt.grid()
    plt.tight_layout()
    plt.show()

